logging:
  level:
    ROOT: INFO
    com.goudong: DEBUG
server:
  port: 10000
spring:
  application:
    name: goudong-gateway-server
  # json日期格式化
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.74.128:8848
    sentinel:
      transport:
        dashboard: 192.168.74.128:8080 #配置Sentinel dashboard地址
        port: 8720
    gateway:
      discovery:
        locator:
          enabled: true # 开启从注册中心动态创建路由的功能，利用微服务名进行路由
          lower-case-service-id: true #使用小写服务名，默认是大写
      routes:
        - id: goudong-oauth2-server
          uri: lb://goudong-oauth2-server
          predicates:
            - Path=/api/oauth2/**
        - id: goudong-user-server
          uri: lb://goudong-user-server
          predicates:
            - Path=/api/user/** #断言，路径相匹配的进行路由 多个用逗号分隔（或者）
        - id: goudong-message-server
          uri: lb://goudong-message-server
          predicates:
            - Path=/api/message/** #断言，路径相匹配的进行路由
        - id: goudong-file-server
          uri: lb://goudong-file-server
          predicates:
            - Path=/api/file/** #断言，路径相匹配的进行路由
        - id: goudong-bpm-server
          uri: lb://goudong-bpm-server
          predicates:
            - Path=/api/bpm/** #断言，路径相匹配的进行路由
  redis:
    password: "${REDIS_PASSWORD}"
    timeout: 3000
    sentinel:
      master: mymaster
      nodes:
        - 192.168.74.128:26379
        - 192.168.74.128:26380
        - 192.168.74.128:26381
    lettuce:
      pool:
        max-active: 100 # 连接池最大连接数（使用负值表示没有限制）
        max-idle: 100 # 连接池中的最大空闲连接
        min-idle: 50 # 连接池中的最小空闲连接
        max-wait: 6000 # 连接池最大阻塞等待时间（使用负值表示没有限制）

ribbon:
  # 请求建立连接超时时间，单位：毫秒，默认：2000
  ConnectTimeout: 3000
  # 读取数据超时时间长，单位：毫秒，默认：5000
  # 这里设置为10秒，表示请求发出后，超过10秒没有读取到数据时请求超时
  ReadTimeout: 10000
  # 对所有操作都进⾏重试，默认：false
#  OkToRetryOnAllOperations: false
#  # 对同一个实例的最大重试次数，默认：0
#  MaxAutoRetries: 1
#  # 切换实例重试的最大次数，默认：1
#  MaxAutoRetriesNextServer: 1
