logging:
  config: classpath:log4j2/log4j2-dev.xml
  level:
    ROOT: INFO
    com.goudong: INFO
    com.goudong.gateway: DEBUG
server:
  port: 10000
spring:
  profiles:
    active: dev
  application:
    name: goudong-gateway-server
  # json日期格式化
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        dashboard: localhost:8080 #配置Sentinel dashboard地址
        port: 8720
    gateway:
      discovery:
        locator:
          enabled: true # 开启从注册中心动态创建路由的功能，利用微服务名进行路由
          lower-case-service-id: true #使用小写服务名，默认是大写
      routes:
        - id: goudong-oauth2-server
          uri: lb://goudong-oauth2-server
          predicates:
            - Path=/api/oauth2/**
        - id: goudong-user-server
          uri: lb://goudong-user-server
          predicates:
            - Path=/api/user/** #断言，路径相匹配的进行路由 多个用逗号分隔（或者）
        - id: goudong-message-server
          uri: lb://goudong-message-server
          predicates:
            - Path=/api/message/** #断言，路径相匹配的进行路由
  redis:
    database: 0   # Redis数据库索引（默认为0）
    host: 127.0.0.1 # Redis服务器地址
    port: 6379
    password: ${REDIS_PASSWORD}
    timeout: 3000
ribbon:
  ReadTimeout: 5000 #建立连接所用时间（避免超时）
  ConnectTimeout: 5000 #连接后接口调用时间（避免超时）
