logging:
  config: classpath:log4j2/log4j2-dev.xml
  level:
    ROOT: INFO
    com.goudong.oauth2: DEBUG
    com.goudong: INFO
server:
  port: 10003
  servlet:
    context-path: /api/oauth2
spring:
  application:
    name: goudong-oauth2-server
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.74.128:8848 # nacos服务集群
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.74.128:3306/goudong_user?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&createDatabaseIfNotExist=true
    username: ${MYSQL_USERNAME}
    password: "${MYSQL_PASSWORD}"
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          time_zone: GMT+8
  redis:
    password: "${REDIS_PASSWORD}"
    timeout: 3000
    sentinel:
      master: mymaster
      nodes:
        - 192.168.74.128:26379
        - 192.168.74.128:26380
        - 192.168.74.128:26381
    lettuce:
      pool:
        max-active: 100 # 连接池最大连接数（使用负值表示没有限制）
        max-idle: 100 # 连接池中的最大空闲连接
        min-idle: 50 # 连接池中的最小空闲连接
        max-wait: 6000 # 连接池最大阻塞等待时间（使用负值表示没有限制）
  ## flyway数据迁移
  flyway:
    #是否开启
    enabled: true
    baseline-version: 0
    baseline-on-migrate: true
    table: goudong_oauth2_server_flyway_schema_history

ribbon:
  ReadTimeout: 5000 #建立连接所用时间（避免超时）
  ConnectTimeout: 5000 #连接后接口调用时间（避免超时）
management:
  endpoint:
    health:
      enabled: true

knife4j:
  enable: true         # 是否开启Knife4j增强模式，默认值为false
  production: false    # 生产环境开启
  basic:
    enable: true       # BasicHttp功能，默认为false
    username: knife4j  # 用户名
    password: knife4j  # 密码
  setting:             # 前端Ui的个性化配置属性
    enableDebug: true  # 启用调试，默认为true 无效


# 配置commons
########################################################################################################################
commons:
  # 配置白名单
  whitelist:
    enable: true
    sleep: 15
    failure-retry-num: 5
  # 配置api资源
  api-resource:
    enable: true

# 配置oauth2
########################################################################################################################
oauth2:
  # 配置令牌失效时长
  token-expires:
    enableRepeatLogin: false
    # 浏览器
    browser:
      access: 1
      access-time-unit: hours
      refresh: 2
      refresh-time-unit: days

  # 重定向页面配置
  redirect-page:
    bind-page: http://192.168.74.128:9998/bindPage.html
    transition-page: http://192.168.74.128:9998/transition.html
    index-page: http://192.168.74.128:9998/index.html