logging:
  config: classpath:log4j2/log4j2-dev.xml
  level:
    ROOT: INFO
    com.goudong: DEBUG

server:
  port: 10003
  servlet:
    context-path: /api/oauth2
spring:
  application:
    name: goudong-oauth2-server
  profiles:
#    active: dev
  main:
    allow-bean-definition-overriding: true
  security:
    oauth2:
      client:
        registration:
          github:
            client-id:
            client-secret:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 # nacos服务集群
    alibaba:
      seata:
        tx-service-group: my_test_tx_group #配置事务分组；nacos的service.vgroupMapping.my_test_tx_group=default
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/goudong_user?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&createDatabaseIfNotExist=true
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          time_zone: GMT+8
  redis:
    database: 0
    host: localhost
    port: 6379
    password: 123456

  ## flyway数据迁移
  flyway:
    #是否开启
    enabled: true
    baseline-version: 0
    baseline-on-migrate: true
    table: goudong_oauth2_server_flyway_schema_history
# redisson配置
redisson:
  password: ${spring.redis.password}
  singleServerConfig:
    address: ${spring.redis.host}:${spring.redis.port}

ribbon:
  ReadTimeout: 5000 #建立连接所用时间（避免超时）
  ConnectTimeout: 5000 #连接后接口调用时间（避免超时）
management:
  endpoint:
    health:
      enabled: true
knife4j:
  enable: true         # 是否开启Knife4j增强模式，默认值为false
  production: false    # 生产环境开启
  basic:
    enable: true       # BasicHttp功能，默认为false
    username: knife4j  # 用户名
    password: knife4j  # 密码
  setting:             # 前端Ui的个性化配置属性
    enableDebug: true  # 启用调试，默认为true 无效

## seata server相关配置
########################################################################################################################
seata:
  registry: #配置seata的注册中心，告诉微服务怎么去访问seate server
    type: nacos
    nacos:
      server-addr: 127.0.0.1:8848 # seata server 所注册的nacos地址
      application: seata-server # 服务名
      group: SEATA_GROUP # seata server 所在的分组
  config: # 配置seata的配置中心，可以读取关于 seata client的一些配置
    type: nacos
    nacos:
      server-addr: 127.0.0.1:8848
      group: SEATA_GROUP

# 配置commons
commons:
  # 配置白名单
  whitelist:
    enable: true
    sleep: 15
    failure-retry-num: 5
  # 配置api资源
  api-resource:
    enable: true

# 配置oauth2
oauth2:
  # 配置令牌失效时长
  token-expires:
    enableRepeatLogin: false
    # 浏览器
    browser:
      access: 1
      access-time-unit: minutes
      refresh: 2
      refresh-time-unit: days

  # 重定向页面配置
  redirect-page:
    bind-page: http://localhost:9998/bindPage.html
    transition-page: http://localhost:9998/transition.html
    index-page: http://localhost:9998/index.html