logging:
  level:
    ROOT: INFO
    com.goudong: DEBUG
    org.springframework.web.servlet.DispatcherServlet: DEBUG

server:
  port: 10001
  servlet:
    context-path: /api/user
spring:
  main:
    allow-bean-definition-overriding: true #重命名其中一个 bean 或启用覆盖
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false #工程中的资源文件建立映射
  application:
    name: goudong-user-server #微服务名
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 # nacos服务集群
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          time_zone: GMT+8
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/goudong_user?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&createDatabaseIfNotExist=true
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}

  redis:
    database: 0   # Redis数据库索引（默认为0）
    host: 127.0.0.1 # Redis服务器地址
    port: 6379
    password: ${REDIS_PASSWORD}
    timeout: 3000

  ## flyway数据迁移
  flyway:
    #是否开启
    enabled: true
    baseline-version: 0
    baseline-on-migrate: true
    table: goudong_user_server_flyway_schema_history

ribbon:
  ReadTimeout: 5000 #建立连接所用时间（避免超时）
  ConnectTimeout: 5000 #连接后接口调用时间（避免超时）

knife4j:
  enable: true         # 是否开启Knife4j增强模式，默认值为false
  production: false    # 生产环境开启
  basic:
    enable: true       # BasicHttp功能，默认为false
    username: knife4j  # 用户名
    password: knife4j  # 密码
  setting:             # 前端Ui的个性化配置属性
    enableDebug: true  # 启用调试，默认为true 无效

# 配置commons
########################################################################################################################
commons:
  # 配置白名单
  whitelist:
    enable: false
    sleep: 15
    failure-retry-num: 5
  # 配置api资源
  api-resource:
    enable: false
  hide-menu:
    enable: true
  goudong:
    web:
      enable: true
