server:
  port: 10002
  servlet:
    context-path: /api/message # 访问应用统一前缀
spring:
  profiles:
    active: dev
  application:
    name: goudong-message-server
  mvc:
    throw-exception-if-no-handler-found: true #出现错误时, 直接抛出异常
  resources:
    add-mappings: false #不要为我们工程中的资源文件建立映射
  # json日期格式化
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  ## Redis
  redis:
    database: 0   # Redis数据库索引（默认为0）
    host: 127.0.0.1 # Redis服务器地址
    port: 6379
    password: ${REDIS_PASSWORD}
    timeout: 3000

  #############
  # rabbitMQ
  ##############
  rabbitmq:
#    host: 127.0.0.1  # mq ip地址
    host: 47.108.31.41  # mq ip地址
    port: 5672 # 端口 默认5672
    username: ${RABBITMQ_USERNAME} # 用户名
    password: ${RABBITMQ_PASSWORD} # 密码
    virtual-host: /goudong-host
    # 开启ACK
    listener:
      direct:
        acknowledge-mode: manual
        retry:
          enabled: true # 是否支持重试
      simple:
        acknowledge-mode: manual
        retry:
          enabled: true # 是否支持重试
    publisher-confirm-type: simple # 开启发送确认
    publisher-returns: true #开启发送失败退回
    template:
      mandatory: true

  ##############
  # 发送邮件配置 #
  #############
  mail:
    host: smtp.qq.com
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    port: 587 #端口号465或587
    protocol: smtp
    default-encoding: UTF-8
    smtp:
      connectiontimeout: 5000
      timeout: 3000
      writetimeout: 5000

alibaba:
  message:
    accessKeyId: ${ALIBABA_MESSAGE_ACCESS_KEY_ID}
    accessKeySecret: ${ALIBABA_MESSAGE_ACCESS_KEY_SECRET}
    signName: ${ALIBABA_MESSAGE_SIGN_NAME}
    templateCode: ${ALIBABA_MESSAGE_TEMPLATE_CODE}