logging:
  config: classpath:log4j2/log4j2.xml
  level:
    ROOT: INFO
    com.goudong.modules: DEBUG
    com.goudong: DEBUG

server:
  port: 20000
  servlet:
    context-path: /api/seata
spring:
  main:
    allow-bean-definition-overriding: true #重命名其中一个 bean 或启用覆盖
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false #工程中的资源文件建立映射
  application:
    name: seata-client-a #微服务名
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 # nacos服务集群
    alibaba:
      seata:
        tx-service-group: my_test_tx_group #配置事务分组；nacos的service.vgroupMapping.my_test_tx_group=default
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          time_zone: GMT+8
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/seata_client_a?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&createDatabaseIfNotExist=true
    username: root
    password: "l(=8gp_04h*&"

  ## flyway数据迁移
  flyway:
    #是否开启
    enabled: true
    baseline-version: 0
    baseline-on-migrate: true
    table: flyway_schema_history

ribbon:
  ReadTimeout: 5000 #建立连接所用时间（避免超时）
  ConnectTimeout: 5000 #连接后接口调用时间（避免超时）


## seata server相关配置
########################################################################################################################
seata:
  registry: #配置seata的注册中心，告诉微服务怎么去访问seate server
    type: nacos
    nacos:
      server-addr: 127.0.0.1:8848 # seata server 所注册的nacos地址
      application: seata-server # seata 资源管理器 的服务名
      group: SEATA_GROUP # seata server 所在的分组
  config: # 配置seata的配置中心，可以读取关于 seata client的一些配置
    type: nacos
    nacos:
      server-addr: 127.0.0.1:8848
      group: SEATA_GROUP
