spring:
  rabbitmq:
    address: 127.0.0.1:5672 #多个以逗号分隔，
    username: admin # 用户名
    password: 123456 # 密码
    virtual-host: virtual01 # 需要提前创建虚拟主机，并设置权限
    publisher-confirm-type: CORRELATED # 开启消息确认，确认消息已发送到交换机（Exchange）
    publisher-returns: true #开启发送失败退回，确认消息已发送到队列
    # 开启ACK
    listener:
      simple:
        acknowledge-mode: manual # 开启手动确认
        retry:
          enabled: true # 是否支持重试
      direct:
        acknowledge-mode: manual # 开启手动确认
        retry:
          enabled: true # 是否支持重试
    template:
      mandatory: true # 强制发送消息，如果消息没有路由到一个队列，就会回调 RabbitTemplate.ReturnCallback.returnedMessage()
      retry:
        enabled: true # 是否支持重试
