spring:
  redis:
    # 这个密码其实就是redis哨兵密码，如果哨兵配置了这里就需要填写（主节点和从节点密码都设置一致）
    password: 123456
    timeout: 30000
    database: 0
    sentinel:
      master: mymaster
      # 这里可以配置字符串，也可以配置数组
      # nodes: 10.168.60.100:26379,10.168.60.100:26380,10.168.60.100:26381
      nodes:
        - 192.168.0.138:6379
        - 192.168.0.138:6380
        - 192.168.0.138:6381
    lettuce:
      pool:
        max-active: 100 # 连接池最大连接数（使用负值表示没有限制）
        max-idle: 100 # 连接池中的最大空闲连接
        min-idle: 50 # 连接池中的最小空闲连接
        max-wait: 6000 # 连接池最大阻塞等待时间（使用负值表示没有限制）
