server:
  port: 8080
spring:
  application:
    name: xxl-job

xxl:
  job:
    enable: true
#    access-token:
    admin:
      ### 调度中心部署根地址 [选填]：如调度中心集群部署存在多个地址则用逗号分隔。执行器将会使用该地址进行"执行器心跳注册"和"任务结果回调"；为空则关闭自动注册；
      addresses: http://192.168.74.128:8080/xxl-job-admin
    ### 执行器通讯TOKEN [选填]：非空时启用；
    executor:
      ### 执行器AppName [选填]：执行器心跳注册分组依据；为空则关闭自动注册
      app-name: ${spring.application.name}

