logging:
  level:
    ROOT: INFO
    com.goudong: DEBUG
    org.springframework.web.servlet.DispatcherServlet: DEBUG

server:
  port: 10004
  servlet:
    context-path: /api/file
spring:
  main:
    allow-bean-definition-overriding: true #重命名其中一个 bean 或启用覆盖
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false #工程中的资源文件建立映射
  application:
    name: goudong-file-server #微服务名
#  # json日期格式化
#  jackson:
#    date-format: yyyy-MM-dd HH:mm:ss
#    time-zone: GMT+8
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848 # nacos服务集群
  servlet:
    multipart:
      # 设置值为-1，不限制大小
      max-request-size: -1
      max-file-size: -1
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/goudong_file?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&createDatabaseIfNotExist=true
    username: ${MYSQL_USERNAME}
    password: "${MYSQL_PASSWORD}"
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialSize: 5
    maxActive: 50
    minIdle: 0
    maxWait: 60000
    useUnfairLock: true # 禁用公平锁
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: GMT+8
  redis:
    database: 0   # Redis数据库索引（默认为0）
    host: 127.0.0.1 # Redis服务器地址
    port: 6379
    password: ${REDIS_PASSWORD}
    timeout: 3000
  flyway:
    enabled: true
    baseline-version: 0
    baseline-on-migrate: true
    table: goudong_file_server_flyway_schema_history
## redisson配置
#redisson:
#  password: ${spring.redis.password}
#  singleServerConfig:
#    address: ${spring.redis.host}:${spring.redis.port}

ribbon:
  ReadTimeout: 5000 #建立连接所用时间（避免超时）
  ConnectTimeout: 5000 #连接后接口调用时间（避免超时）


knife4j:
  enable: true         # 是否开启Knife4j增强模式，默认值为false
  production: false    # 生产环境开启
  basic:
    enable: true       # BasicHttp功能，默认为false
    username: knife4j  # 用户名
    password: knife4j  # 密码
  setting:             # 前端Ui的个性化配置属性
    enableDebug: true  # 启用调试，默认为true 无效

# 自定义配置
commons:
  whitelist:
    enable: false

file:
  upload:
    enable-full-path-model: true
    root-dir: 'd:/goudong-file-server'
    jpg:
      length: 1
      file-length-unit: gb
    mp4:
      length: 100
      file-length-unit: mb
    avi:
      length: 1
      file-length-unit: mb
feign:
  httpclient:
    enabled: true


goudong:
  web:
    api-log:
      print-log-limit:
        head-params:
          Authorization: true
