server:
  port: 10001
  servlet:
    context-path: /api/wx/central-control

logging:
  level:
    ROOT: INFO
    com.goudong: DEBUG # 包路径: 日志级别

spring:
  main:
    allow-bean-definition-overriding: true #重命名其中一个 bean 或启用覆盖
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false #工程中的资源文件建立映射
  application:
    name: goudong-wx-central-control-server #微服务名

  redis:
    database: 0   # Redis数据库索引（默认为0）
    host: 127.0.0.1 # Redis服务器地址
    port: 6379
    password: ${REDIS_PASSWORD}
    timeout: 3000

knife4j:
  enable: true         # 是否开启Knife4j增强模式，默认值为false
  production: false    # 生产环境开启
  basic:
    enable: true       # BasicHttp功能，默认为false
    username: knife4j  # 用户名
    password: knife4j  # 密码
  setting:             # 前端Ui的个性化配置属性
    enableDebug: true  # 启用调试，默认为true 无效
# 配置wx
########################################################################################################################
wx:
  app:
    testAppId: wx1948fa77ad11a423
    testAppSecret: 410d996604e66d6278d1e5a4d0f49e9c

# 配置commons
########################################################################################################################
commons:
  # 配置白名单
  whitelist:
    enable: false
    sleep: 15
    failure-retry-num: 5
  # 配置api资源
  api-resource:
    enable: false
  hide-menu:
    enable: true
  goudong:
    web:
      enable: true
